export {default as Hero} from './hero'
export {default as Custom} from './custom'
export {default as CoreValue} from './core-value'
export {default as MeetTheTeam} from './meet-the-team'
export {default as Partner} from './partner'
export {default as FeaturedWorks} from './featured-works'